### PR TITLE
__setattr__ will now munchify() any provided dict

### PR DESCRIPTION
**Pull request by kbni**
I'm not sure if this is the best way to go about it, but I need `Munch` to `munchify` any dicts it is assigned:

```python
>>> from munch import *
>>> m = Munch()
>>> m.foo = {'bar':'baz'}
>>> m
Munch({'foo': Munch({'bar': 'baz'})})
>>> m.foo.bar
'baz'
```

### CODE REVIEW

**Comment by vmalloc** [comment]
I'm not 100% sure this makes sense. For many purposes, this seems like a valid logic for the user to want:
```
m = Munch()
data = {...}
m.data = data
assert m.data is data
```
And this change will break that assumption...

**Comment by kbni** [comment]
Perhaps this would be a decent compromise?

Doesn't really matter I suppose, I could just as easily add this to my helper library.. but perhaps someone else desires this functionality.

**Comment by vmalloc** [comment]
@kbni the build is failing because of Python 2.6. I pushed a change to master dropping 2.6, 3.3 and 3.4 support. Can you rebase on top of it and push again?

**Comment by kbni** [comment]
@vmalloc Rebased as requested, but as you suggested this functionality is pretty easy to include on a per-project basis: https://gist.github.com/kbni/2af872cb87f26d754a22aa04f70f08fc

**Comment by vmalloc** [comment]
@kbni so are you ok with leaving it as a "cookbook recipe" instead of having it merged to the source itself?

**Comment by kbni** [comment]
@vmalloc Up to you. Would be nice to be included, but I'll live without! :)

**Comment by vmalloc** [comment]
@kbni I think I'll go ahead and merge it. However this has merge conflicts at the moment. Can you rebase the PR please?

**Comment by vmalloc** [comment]
Thanks for contributing!

**Pull request merged**
