### PR TITLE
Added RecursiveMunch object.

### PR DESCRIPTION
**Pull request by GuillaumeRochette**
Hi,

I felt the need to have a RecursiveMunch class, which is similar to DefaultFactoryMunch, except that it creates an instance of itself to generate values for missing keys, instead of a user-specified function.

Regards,

Guillaume Rochette

### CODE REVIEW

**Comment by ayalash** [comment]
@GuillaumeRochette Thanks for contributing.

**Comment by ayalash** [comment]
Thanks

**Comment by GuillaumeRochette** [comment]
Hi,
Sorry, I've realised that I did not overload the copy() method, which causes an error.
Here is a corrected version:

```py
class RecursiveMunch(DefaultFactoryMunch):
    """A Munch that calls an instance of itself to generate values for
        missing keys.

        >>> b = RecursiveMunch({'hello': 'world!'})
        >>> b.hello
        'world!'
        >>> b.foo
        RecursiveMunch(RecursiveMunch, {})
        >>> b.bar.okay = 'hello'
        >>> b.bar
        RecursiveMunch(RecursiveMunch, {'okay': 'hello'})
        >>> b
        RecursiveMunch(RecursiveMunch, {'hello': 'world!', 'foo': RecursiveMunch(RecursiveMunch, {}),
        'bar': RecursiveMunch(RecursiveMunch, {'okay': 'hello'})})
    """

    def __init__(self, *args, **kwargs):
        super(RecursiveMunch, self).__init__(RecursiveMunch, *args, **kwargs)

    @classmethod
    def fromDict(cls, d):
        # pylint: disable=arguments-differ
        return munchify(d, factory=cls)

    def copy(self):
        return type(self).fromDict(self)
```

**Comment by ayalash** [comment]
@GuillaumeRochette Fixed
Thanks again

**Pull request merged**
